
# Slf4j 로깅 레벨 : Trace > Debug > Info > Warn > Error > Fatal

spring:
  jpa:
    hibernate:
      ddl-auto: create # 운영환경에서는 none
    properties:
      hibernate:
        format_sql: true


logging:
  level:
    com.example.todo: DEBUG
    org.hibernate.SQL: DEBUG